version: '3.8'

services:
  fidora:
    container_name: fidora
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Development specific overrides:
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./tsconfig.json:/app/tsconfig.json
      - ./nodemon.json:/app/nodemon.json
      # Use an anonymous volume for node_modules
      - /app/node_modules
      # Share the dist directory for hot reloading
      - ./dist:/app/dist
    # No need for command override as it's in Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DEBUG=true
    # Keep the container running
    tty: true
    stdin_open: true
    # Restart on failure
    restart: unless-stopped
